### PR TITLE
Add Method to Create New Comment on Pull Request

### PR DESCRIPTION
**Pull request by JoeStanleySEL**
I've only addressed the method itself, and some little README formatting stuff. I'm not sure exactly how I should "plug into" the testing framework, or what needs to be done there. Could you provide some recommendations on how I can add to it?

Thank you!

### CODE REVIEW

**Comment by JoeStanleySEL** [comment]
Can tests be run without connection to a valid Bitbucket server? If so, I wonder if it would be possible to automate them with a Github action?

**Comment by JasonKempSEL** [comment]
Yes, the tests use mocks to avoid connecting to a real Bitbucket. They can be run with unittest's discover option. `python3 -m unittest discover .` from the root of the repo.

**Comment by JoeStanleySEL** [comment]
@JasonKempSEL thank you so much! Forgive my ignorance on this. I'm still not entirely confident in my understanding of the test structure to make a new unittest for this added functionality. If you have suggestions, or any tips. I'd be happy to add it.

For now, though I'm going to open this PR. I will work (in a separate branch) to see if I can't get a note added on how to run the tests, and a GH-action script to run the tests with coverage.

**Review by JasonKempSEL — APPROVED** [review]
Sorry for the delay in reviewing this. It's a good start, though `path` isn't a URL param, but part of the JSON body. I'll fix it up and add some other features

**Pull request merged**
